name = "squirtle"
version = "1.0.0"

[dependencies]
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_stdlib = ">= 0.65.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
